#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer with modifications for #! by Jess Robertson
# Repository: https://github.com/jessrobertson/xmonad-conf
#

#
# TRAY ICON SOFTWARE
#

# Empathy chat client (-h: start hidden, -n: don't connect on launch)
# if [ -z "$(pgrep pidgin)" ] ; then
#      pidgin &
# fi

# Fix screen setup
#/home/jrobertson/bin/fix_screen &

# Remmina remote desktop connection client (-i: start hidden)
#if [ -z "$(pgrep remmina)" ] ; then
#    remmina -i &
#fi

# Network manager, so we don't have to configure wifi at the command line.
#if [ -z "$(pgrep wicd-client)" ] ; then
#    wicd-gtk &
#fi

# Applet for managing print jobs from the tray.
#if [ -z "$(pgrep system-config-printer-applet)" ] ; then
#    system-config-printer-applet &
#fi

# Clipboard manager
#if [ -z "$(pgrep clipit)" ] ; then
#	clipit &
#fi

# Volume icon
#if [ -z "$(pgrep pnmixer)" ] ; then
#	pnmixer &
#fi

# Synergy server
# if [ -z "$(pgrep synergyc)" ] ; then
# 	synergyc greygoose &
# fi

# Mail
#if [ -z "$(pgrep icedove)" ] ; then
#	icedove &
#fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested) 
# if [ -z "$(pgrep synapse)" ] ; then
#     synapse -s &
# fi

# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
# 
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.
#
# export SSH_ASKPASS="/usr/bin/ssh-askpass"
# cat /dev/null | ssh-add &

# I disable the middle mouse button because otherwise I constantly 
# accidentally paste unwanted text in the middle of my code while scrolling. 
# Note that the id of the mouse device may be different depending on 
# which usb port it is plugged into! To find it, use:
# xinput list |grep 'id='
# In the following command, the id is the first argument, the rest is 
# the remapping.

# Commented by default as it is assumed many users will not want this.
# xinput set-button-map 10 1 0 3 4 5 6 7

# Have statler say a little adage
#(sleep 120s && cb-fortune) &
